//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ssms.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "15.3.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        //[global::System.Configuration.DefaultSettingValueAttribute("Data Source=MI-GUOTENGFENG\\SQLEXPRESS;Initial Catalog=ssms1;Integrated Security=True")]

		//供lts连接数据库使用的数据库配置
		#if false
		[global::System.Configuration.DefaultSettingValueAttribute("Data Source=.;Initial Catalog=ssms1;Integrated Security=True")]
		#else
		[global::System.Configuration.DefaultSettingValueAttribute("Data Source=.; Initial Catalog=ssms1; UID=sa;PASSWORD=123456;pooling=false; ")]
		
		#endif
		public string ssmsConnectionString {
            get {
                return ((string)(this["ssmsConnectionString"]));
            }
        }
    }
}
